server.port=8350

# Database connection properties
#yenaye2665@hlkes.com
#yenaye2665@hlkes.comQ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-damp-sound-al9k9ekh-pooler.c-3.eu-central-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DcWVe4IHFk5Q

# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true

upload.dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB

it.step.app.jwtSecret=404E635266556A586E3272357538788652F413F4428472B4B6250645367566B5970